# Generated by Django 5.1.2 on 2024-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
