# Generated by Django 5.1.2 on 2024-12-20 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bedbooking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateField(auto_now_add=True),
        ),
    ]
