# Generated by Django 5.1.2 on 2024-12-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_visitor_check_in_time_visitor_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
