# Generated by Django 5.1.2 on 2024-12-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_visitor_checked_out_visitor_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
