# Generated by Django 5.1.2 on 2024-12-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.intake'),
        ),
    ]
